# Generated by Django 6.0.4 on 2026-04-24 01:08

import envios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0004_empleado_rutas_asignadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomienda',
            name='codigo',
            field=models.CharField(max_length=20, unique=True, validators=[envios.validators.validar_codigo_encomienda]),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='peso_kg',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[envios.validators.validar_peso_positivo]),
        ),
    ]
