# Generated by Django 6.0.4 on 2026-05-14 23:38

import django.core.validators
import envios.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0006_alter_encomienda_costo_envio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomienda',
            name='peso_kg',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[envios.validators.validar_peso_positivo, django.core.validators.MinValueValidator(Decimal('0.01'), message='El peso minimo es 0.01 kg')]),
        ),
    ]
